# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f4e4333269d6d99ee2bb2d2a1109bccac5e51cf2fd83fd89f7928e0598aa0c9a55b16c86fed202eb2b6e70a717ab36bd3299cbba6a0adda319c8011ee4323c8

test:
  secret_key_base: b83f079cb282f896ecb7d224c7198a0fcf3f6ee46aa54c7cab7c57883cb23d89d8bac70e25314a058c90386bd7223e897d47fa65d2efd2db0c8a23ebf3881513

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
